# Generated by Django 3.0.7 on 2020-06-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('image', models.CharField(max_length=55)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
