# Generated by Django 3.0.7 on 2020-07-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200710_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, verbose_name='Name')),
                ('project_description', models.CharField(max_length=200, verbose_name='Description')),
                ('project_content', models.CharField(max_length=200, verbose_name='Content')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('project_image', models.FileField(blank=True, null=True, upload_to='', verbose_name=' Add Image')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_author',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_content',
            field=models.CharField(max_length=200, verbose_name='Comment'),
        ),
    ]
