# Generated by Django 3.0.7 on 2020-07-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20200710_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='project_content',
            field=models.TextField(verbose_name='Content'),
        ),
    ]
