# Generated by Django 3.0.7 on 2020-07-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50, verbose_name='Name')),
                ('project_description', models.CharField(max_length=200, verbose_name='Description')),
                ('project_content', models.TextField(verbose_name='Content')),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('project_image', models.FileField(blank=True, null=True, upload_to='', verbose_name=' Add Image')),
            ],
        ),
    ]
