# Generated by Django 3.0.7 on 2020-07-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='project_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name=' Add p Image'),
        ),
    ]
